version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    ports:
        - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./mytheme:/opt/keycloak/themes/mytheme
