services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://sso.sikalabs.com/realms/training/protocol/openid-connect/logout?redirect_uri=http://localhost:3000
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=SSO
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=example_client_id
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=example_client_secret
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://sso.sikalabs.com/realms/training/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://sso.sikalabs.com/realms/training/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://sso.sikalabs.com/realms/training/protocol/openid-connect/userinfo
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'foo') && 'Admin' || 'Viewer'
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
