apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-keycloak-training
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: examples/argocd/keycloak-training/apps
    repoURL: https://github.com/ondrejsika/keycloak-training.git
    targetRevision: master
