
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maildev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: maildev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/maildev
    helm:
      releaseName: maildev
      values: |
        host: maildev.k8s.sikademo.com
